### ISSUE TITLE
https://www.phpagebuilder.com/ is not working

### ISSUE THREAD

**Issue by mambax7** [HansSchouten/PHPageBuilder#1]
When I go there, that's the only message I get:

Apache is functioning normally

**Comment by HansSchouten** [comment]
Hi Michael, thanks for your message. I recently started with this project and did not create the info website yet. I now have quickly put something online on [phpagebuilder.com](https://www.phpagebuilder.com) _(built with PHPageBuilder of course)_ and will further expand it in upcoming months, as well as add more documentation.

The project is already usable and will be extended as I add more functionality to the websites for my clients. A first v1.0 release is expected around April.

**Comment by mambax7** [comment]
Thanks for the update! 

I guess, I'll have to wait till April then, because I've tried to make it work, and I couldn't.  I've tried stand-alone, and I tried with Laravel, and with the same result.

Few suggestions:
1) make the route size smaller, because with 512 the "unique" index create MySQL error 1071, because the index is too big
2) you might include in your [boiler plate](https://github.com/HansSchouten/PHPagebuilder-boilerplate), actual data to be imported into the DB, because I had problems figuring out what should I post in "layout" field

It looks promising, so hopefully I'll be able to do some more testing...

Thanks for sharing!

**Comment by HansSchouten** [comment]
Thanks for the suggestions, I will soon look into it.

The issue you have is probably related to your theme structure. The layout field of a page should be the name of the folder which contains the `view.php` or `view.html` of your layout that will be used. I will elaborate more on [creating themes](https://github.com/HansSchouten/PHPagebuilder#create-a-theme) in the docs since it is still missing the majority of currently supported features.

I am currently using the following project structure (starting from the boilerplate):
![boiler plate project structure](https://user-images.githubusercontent.com/5946444/71716153-0ec16380-2e14-11ea-852c-99c0db98d1f2.png)

**Comment by mambax7** [comment]
Awesome!!! Thank you so much! I'll try again this weekend...

**Comment by HansSchouten** [comment]
You're welcome! Feel free to ask any questions, I'd love to help out and process any feedback.
