### ISSUE TITLE
block thumb

### ISSUE THREAD

**Issue by electroheadfx** [HansSchouten/PHPageBuilder#14]
I dont understand how you return the block thumb :
phpb_theme_asset('block-thumbs/' . md5($this->blockSlug) . '/' . md5(file_get_contents($this->getViewFile())) . '.jpg');

is it auto generated by a library I missed ? else not Can I add a thumb filename in block config ?:
return [
    'title' => 'Content01',
    'category' => 'Contents',
    'thumb' => 'Content01.jpg',
];

**Comment by HansSchouten** [comment]
In the Laravel version, I render thumbs using this code: https://github.com/HansSchouten/PHPageBuilder-Laravel-Screenshots. Since it is not working out of the box and depends on your server setup, I did not add it by default. Adding custom images is not yet supported, mainly because I think it is a very tedious task to make these images for each block. As an alternative there is a method to render the thumbs using html5 canvas:

![afbeelding](https://user-images.githubusercontent.com/5946444/83107867-4381d000-a0bf-11ea-963c-1460ef45fc80.png)
