### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Vanguger** [HansSchouten/PHPageBuilder#2]
Hi! I did it according to the documentation, but I have: Page not found. How can I solve this problem?

**Comment by HansSchouten** [comment]
Hi! Thanks for your feedback. I closed the other 2 issues by processing your suggested fixes. Page not found is probably because you did not have created a first page. To do this, log in via `/admin` and create a page with route `/` (which means your homepage). All routes should start with a `/`, like shown in the Website Manager screenshot (https://github.com/HansSchouten/PHPageBuilder#website-manager). Soon I will add dummy data with a few initial pages which would help better understand and guide the process.

**Comment by Vanguger** [comment]
I couldn't log in to the admin panel. But I found the reason in the file .htaccess
I deleted a few lines in this file, on my local server (redirect https, www)

**Comment by chichenchuang** [comment]
I install it with documentation. Page not found was happened via /admin. How do I fix it through .htaccess file? 
Thanks

**Comment by witu9217** [comment]
I am having the same issue i cannot view the /admin page. I am getting this msg on the screen

PHPageBuilder page not found. Check your URL: http://localhost/laraveltest/public/admin

Does anybody have solution for this?

Thanks

**Comment by Atif-Bashir-1998** [comment]
Go to the .env file of your project (this file is inside the root directory of your project).
Change the APP_URL and you will be able to access the /admin

**Comment by Atif-Bashir-1998** [comment]
> I install it with documentation. Page not found was happened via /admin. How do I fix it through .htaccess file?
> Thanks

Go to the .env file of your project (this file is inside the root directory of your project).
Change the APP_URL and you will be able to access the /admin

**Comment by maiman-1** [comment]
Also coming up with this error on the laravel-pagebuilder. Cannot access admin so, cannot login. What should I change the APP_URL to? Currently it is set to "http://localhost"

**Comment by quanvm88** [comment]
Hi HansSchouten!

I added one page success. But when I clicked button view page got error: PHPageBuilder page not found. Check your URL: http://localhost:925/xin-chao

Help me please! Thank so much!
