### ISSUE TITLE
add default collapsed category 

### ISSUE THREAD

**Issue by dsultanr** [HansSchouten/PHPageBuilder#42]
is it possible to add any option into config.php of the block to prevent auto-expand the category of the block (not to add gjs-open class)?

**Comment by HansSchouten** [comment]
Yes this is possible, I will soon add this option.

**Comment by HansSchouten** [comment]
I just found out to my surprise that there is no option for that in GrapesJS. [This](https://github.com/artf/grapesjs/issues/446#issuecomment-339311523) seems to be the only way, but we cannot easily pass preferences to sidebar for performing this after page load. Also to be able to prevent auto expand in a block config is a bit unclear, since you have multiple blocks in a category.

For now I have added an improvement that on searching for blocks, categories without matches will be automatically hidden. Hopefully this helps as well.

**Comment by dsultanr** [comment]
sad, thanks
