### ISSUE TITLE
PHP Page Builder not found

### ISSUE THREAD

**Issue by adityabimo29** [HansSchouten/PHPageBuilder#67]
when I open index or admin always shows "PHPageBuilder page not found. Check your URL: http://localhost/lhost/lap ".

**Comment by HansSchouten** [comment]
Please check the base URL in the [config file](https://github.com/HansSchouten/PHPageBuilder/blob/master/config/config.example.php#L13). In your case it should be `http://localhost/lhost` I think.

**Comment by adityabimo29** [comment]
in my config file is still 'base_url' => 'http://localhost', but if i change to 'base_url' => 'http://localhost/lap', error will became PHPageBuilder page not found. Check your URL: http://localhost/lap/lap

**Comment by HansSchouten** [comment]
It has to do with installing the project in a subdirectory instead of your webserver's webroot. Strange, it should be possible as I have tried it without issues before, however I don't have such environments at the moment to quickly test this out. Maybe you can try with and without subdirectory or try debugging the two [phpb methods](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/PHPageBuilder.php#L291) that are called in the error you have.
Also ensure your .htaccess is correct according to the [boilerplate](https://github.com/HansSchouten/PHPagebuilder-boilerplate).

**Comment by adityabimo29** [comment]
thank you for your replies. after change url to http://localhost:8000 it works
