### ISSUE TITLE
Example blocks and some info

### ISSUE THREAD

**Issue by daebak74** [HansSchouten/PHPageBuilder#8]
Hi,
I just found your package and really congratulations.

Is possible to have a full layout with more example blocks as your screenshot for reference ?

Than there is some question that I would to make because I didn't find anything in doc.

- In website manager there is Menu what is that ?

- In page builder there is a tab settings but I don't find any reference in the doc.

- a view.php ot editable in Editor I suppose for create block NO static HTML content maybe using a framework or with dynamic data from db, it's correct ?

I tried to add a new folder in theme but I can't see in Website Manager Layout Select need to add in config.php ? How ?

Thanks you!

**Comment by HansSchouten** [comment]
Hi, thanks for your comment. I am planning to create a full (bootstrap) demo theme, however currently I am still in active development and delivering a website using this platform for a client. But I will definitely add a more extensive example theme as soon as I have the time for it.

> In website manager there is Menu what is that

The Menu tab is currently empty, but the idea here is to allow creating menu's for example for the main navigation bar of a website.

> In page builder there is a tab settings but I don't find any reference in the doc.

Thanks I will add this to the docs. Currently it only has an option to set the languages for which you can add web page translations in the page builder, and a setting to re-render icons of each theme block for in the pagebuilder sidebar.

> a view.php ot editable in Editor I suppose for create block NO static HTML content maybe using a framework or with dynamic data from db, it's correct?

Yes, a .html file is if you want content editable text. If you create a .php file, the html elements cannot be directly edited, but it can include serverside rendered html based on DB data for instance. Also you can create a `config.php` file with settings that can be configured from within the pagebuilder. These setting values are then accessible to the .php file.

> I tried to add a new folder in theme but I can't see in Website Manager Layout Select need to add in config.php ? How ?

If you haven't already, take a look here: https://github.com/HansSchouten/PHPagebuilder-boilerplate. You can find the correct theme structure. You need a folder in which you have a `blocks`, `layouts` and `public` folder. Next, you need to edit your `config.php` and set `theme > active_theme` to the name of the folder you are using.

**Comment by daebak74** [comment]
@HansSchouten thank you for your detailed reply.

Good new about your idea to build a full bootstrap theme, most is clear except the last point maybe I didn't explain well.

Yes I checked the doc and the folder example structure and if I add theme > active_theme I can see in the Layout Select in Website Manager my theme. But I think that if I add more theme in select Layout field should show all the theme and not only the theme_active or I am Wrong ?

Other question is about the integration with framework offen I make app with Symfony so how it will be integrated if the framework has a config/.env for config, a public/ for js/css and view/ for template ?

I like the idea and if you have any slack or direct message way for connect I would give an help for speed up the template block/widget coding.

**Comment by HansSchouten** [comment]
> But I think that if I add more theme in select Layout field should show all the theme and not only the theme_active or I am Wrong ?

Switching theme is currently only possible on installing a theme and changing the `active_theme` in the `config.php`. The layout selector is for selecting one of your layouts within the active theme (that are stored in the `Layouts` folder). So, for example you create one layout which always includes a header and footer and another layout for all pages that includes header, footer and a sidebar etc. On creating a new page you can then load these default components within needing to add them manually to every page.

> so how it will be integrated if the framework has a config/.env for config, a public/ for js/css and view/ for template?

I have no experience with Symfony yet, but I do have in Laravel and created a Laravel wrapper for the pagebuilder: https://github.com/HansSchouten/Laravel-Pagebuilder. Maybe you can get some inspiration there and apply it. Instead of the `.env` file, I use a separate config file which is passed to the PHPageBuilder instance. And at the moment I do not use the public and views folder from Laravel, I store all contents in a custom themes folder and refer to that folder in [the configuration](https://github.com/HansSchouten/Laravel-Pagebuilder/blob/master/config/pagebuilder.php).

> I like the idea and if you have any slack or direct message way for connect

Good idea, I will set up a Slack channel for that and link it the Readme. However at the moment I am busy finishing off a project, so I will do that later.

**Comment by extra2005** [comment]
Как редактировать html в конструкторе

**Comment by HansSchouten** [comment]
@extra2005 what do you mean with edit html inside the constructor? What are you trying to achieve
